name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check For PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ env.GITHUB_BASE_REF }}
        run: |
          echo "Check If PR exists for $REF"
          gh pr list --base "$REF" --state open --label "Release $REF"
          if [[ "$(gh pr list --base "$REF" --state open --label "Release $REF")" == "" ]]; then
            echo "Creating PR"
            gh pr create --base beta --label "Release $REF" --title "Release $REF"
          fi