name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
env:
  GITHUB_USER: idex-bot
  GIT_AUTHOR_NAME: idex-bot
  GIT_AUTHOR_EMAIL: support@idex.io
  GIT_COMMITTER_NAME: idex-bot
  GIT_COMMITTER_EMAIL: support@idex.io
jobs:
  pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check For PR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REF: ${{ env.GITHUB_BASE_REF }}
          BASE: main
          GITHUB_USER: idex-bot
          GIT_AUTHOR_NAME: idex-bot
          GIT_AUTHOR_EMAIL: support@idex.io
          GIT_COMMITTER_NAME: idex-bot
          GIT_COMMITTER_EMAIL: support@idex.io
        run: |
          BRANCH=${GITHUB_REF##*/}
          [[ "$BRANCH" == "$BASE" ]] && exit 0;
          if [[ "$BRANCH" == "alpha" ]]; then
            BASE="beta"
          fi
          echo "Check If PR exists for $BRANCH --> $BASE"
          if [[ "$(gh pr list -R "$GITHUB_REPOSITORY" --base "$BASE" --state open --label "Release $BRANCH")" == "" ]]; then
            echo "Creating PR $BRANCH --> $BASE"
            RESULT=$(gh api repos/"${GITHUB_REPOSITORY}"/pulls -F head="$BRANCH" -F base="$BASE" -F title="Release $BRANCH" -F body="This PR was generated automatically.  Merging it will transition $BRANCH into ${BASE}.")
            PR_NUM=$(echo $RESULT | jq -r '.number')
            printf '{"labels": ["Release %s"]}' $BRANCH | gh api repos/"${GITHUB_REPOSITORY}"/issues/"${PR_NUM}"/labels --input -
          fi
  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release